a = ["adaptaciyausa", "adaptaciya_ua_usa", "ads_new_york", "ca_miami_chat", "chatamerika", "chatinnj", "chatinSeattle",
     "chatinsf", "chatnewyork1", "chicagoil", "la_services", "los_angeles_avito", "miamichatik", "miamichatru",
     "movingsf", "multinational_group", "nashaphiladelphia", "nashlosangeles", "nashmiami", "nashny", "newyorkchatru",
     "nyjobsusa", "philadelphiachat", "phillychat", "russianlo", "sacramentocity", "telemarketus", "ukrnewyorkgroup",
     "usachatru", "usaforuz", "usagreen", "usarmenians", "usa_360", "usb_mexico_usa", "uzbeksinusalup",
     "vatandoshim_usa_50_state", "yagonadarchausany", "nomadsfamilyusa", "nashchicago", "mahallanewyorkjobs",
     "mexicousa21", "newyorknash1", "rentcarnomad", "rusoenmexico", "workersnomads", "ads_california",
     "america_new_york", "creditmebel908203131", "dogbanusa", "freeshipping", "horizont24", "jobinmoving", "jobs_usa24",
     "jobsinny", "la_california", "mextous", "miamihotchat", "nomadsboston", "nomadsmiami", "nomadsdc", "nomadsfamily",
     "poputchiki_usa", "russianclassifieds", "teachbkusa", "usa_benefit", "usa_exchange", "usa_job_help",
     "usa_job_helper", "usamexico", "used21cars", "biznesdvigusa", "miamiarea", "newyorkchat24", "newyork_job", "vhi7f",
     "mayami_360", "nomadsfamilyla", "nyjobs_usa", "in_miami", "los_angeles_cal", "LA_biznes", "LosAngeles_life",
     "losangelesdayru", "la_mycity", "jobs1nLA", "olxla1", "California_ru", "la_helps", "la_chat_ru", "LosAngeles_Go",
     "Chat_Work_Los_Angeles", "la_chat_work", "LAchatik", "kvartira_new_york", "new_york_citychat", "NYchatik",
     "NewYork_info", "rentinNewYokkChat", "new_york_avito", "MIAMI_HELP", "maiami_are", "Miami_Avito_Go",
     "Miami_GoTravel", "miamskiyydvizh", "ours_chat_miami2", "MiamiFloridainfo", "miami_helps", "miami_chat_rus",
     "Miami_avito", "businessMiamii", "Jobs1nChicago", "BazMeetChicago", "rentinChicagoChat", "Obshchaya_Sbor_Chikago",
     "chired", "chicago_avito", "chicagoass", "jobs1nSeattle", "Seattle_avito", "seattlered", "rentinSiettleChat",
     "businessSiettle", "SacramentoinChat", "businessSacrament0", "ctatinSacramento", "rentinSacramentoChat",
     "sacramentored", "adaptationinsacramento", "cNecRg9IeLlkNmUx", "Washington_life", "Obmenik_USA", "UsaExchangeChat",
     "exchange_chat_usa", "dhdhdhfhfhfh", "ours_app", "pets_delivery_usa_europe_canada", "Poruchiteli", "poruschitel",
     "Works_usa", "UZimiznikilarCOM", "chat_rusrek_sanfrancisco", "san_francisco_avito", "jobsinSF",
     "rentinSanFranciscoChat", "SanFranciscoinChat", "businessSanFrancisco", "philadelpia_pennsylvania",
     "rentinPhiladelphiaChat", "businessPhiladelphia", "BazMeetNewJersey", "businessNewJersey", "chicagochatik",
     "forum_usa", "ponaehali_USA", "russian_seattle", "gofortravel_chat", "Belkin_Viza", "factumauto",
     "usamexmigration", "mexusalegal", "cdlusachat", "remotework_rw", "columbchat", "from_ru_to_the_usa",
     "los_andjeles", "usadvprogram", "chicagonomads", "netvorkingusa", "usamigration", "relocatedv", "newyorkads",
     "expert1usa", "jobforusa", "newyorkup", "guideusa", "auctionauto_ua", "newyork_myfamily", "aziza19882409",
     "maiyami_valyta", "reklama_new_york", "losangeles_valyta", "usa_legally", "chikago_valyta", "dostavkamir",
     "aaalogistics_chat", "trust_shipping_expert_chat", "newyorkvoice", "edmotorss1", "avto_iz_usa_chat",
     "prigonavto_chat", "usa_womanru", "girlsinusa", "mooreamerica_chat", "truckersusaforum", "visainus", "usa360_it",
     "florida_reklama", "relocate_dv24", "bwfull", "california_los_angeles1", "california_russian", "california123",
     "californiaads", "californiajob", "californiarabota", "californiareklama", "mexicochatik", "miamiavito",
     "America_Money_Change", "MexicoToUSA", "teachBK", "silavpravde555", "USAUMM", "usacbp_adaptation",
     "logistics_chat", "docprep", "usa_custom_garage2", "liveandworkinunsa", "newyorkeusa", "amerika2", "onegood_usa",
     "USA_MALA", "housingnomads", "nomadschicago", "sfnomad", "nomadssd", "housingnomad", "rurusd", "vatandoshim_uz",
     "vatandoshimusa", "rent_miami_rusrek", "LosAngelesInfo", "LAForum24", "Rent_Los_Angeles_RusRek", "los_angeles_LA",
     "renthouselup", "svoiny", "Ukraine_in_USA", "Gorodskoy_chat_NY", "gorodskoy_chat_miami", "WorldCalifornia",
     "Chat_Philadelphia_RusRek", "usa_visa_chat", "autobmg", "kyrgyz_in_usa", "usa_visa_bot23", "libertyauto_ukraine",
     "jobbmg", "visa_family_agency", "yes_us_chat", "chatredinway", "obmenrfuzkg", "ambullychat", "housingbmg",
     "sandiegobmg", "sanfranciscobmg"]

for i in a:
    print(f"@{i}")
