shops_list = [{'name': 'no name'}]

groups_list = [
    "kekajangroup", "adaptaciyausa", "adaptaciya_ua_usa", "ads_new_york", "calosangeles", "ca_miami_chat",
    "chatamerika", "chatinnj", "chatinSeattle", "chatinsf", "chatnewyork1", "chchatua", "chicagoil", "la_services",
    "losangeles2021immigrants", "los_angeles_avito", "los_angeles_ca", "los_angeles_california_usa", "miamichatik",
    "miamichatru", "movingsf", "multinational_group", "nashaphiladelphia", "nashlosangeles", "nashmiami", "nashny",
    "newyorkchatru", "nyjobsusa", "philadelphiachat", "phillychat", "russianlo", "sacramentocity", "telemarketus",
    "ukrnewyorkgroup", "usachatru", "usaforuz", "usagreen", "usarmenians", "usa_360", "usb_mexico_usa",
    "uzbeksinusalup", "vatandoshimuzbus", "vatandoshim_usa_50_state", "vatandoshim_uz", "vatandoshimusa",
    "yagonadarchausany", "nomadsfamilyusa", "kg_america", "nashchicago", "nomadschicago", "sfnomad",
    "mahallanewyorkjobs", "nomadssd", "mexicousa21", "newyorknash1", "rentcarnomad", "rusoenmexico", "workersnomads",
    "ads_california", "america_new_york", "canada_work_life", "creditmebel908203131", "dogbanusa", "freeshipping",
    "horizont24", "housingnomad", "jobinmoving", "jobs_usa24", "jobsinny", "la_california", "liveintheusa", "mextous",
    "miamihotchat", "nomadsboston", "nomadsmiami", "nomadsdc", "nomadsfamily", "poputchiki_usa", "rent_miami_rusrek",
    "russianclassifieds", "teachbkusa", "trucker_cargo", "usa_benefit", "usa_exchange", "usa_job_help",
    "usa_job_helper", "usamexico", "used21cars", "biznesdvigusa", "miamiarea", "newyorkchat24", "newyork_job", "vhi7f",
    "mayami_360", "nomadsfamilyla", "nyjobs_usa", "in_miami", "los_angeles_cal", "LosAngeleschat_ru", "LA_biznes",
    "Los_Angeles_california_usa", "LosAngeles_life", "LosAngelesInfo", "NashLosAngeles", "LAForum24",
    "losangelesfriends", "Los_Angeles_CA", "losangelesdayru", "la_mycity", "Los_Angeles_PrivateClub", "russianlo",
    "jobs1nLA", "Rent_Los_Angeles_RusRek", "olxla1", "los_angeles_LA", "California_ru", "LA_services",
    "multinational_group", "la_helps", "la_chat_ru", "LosAngeles_Go", "Chat_Work_Los_Angeles", "los_work",
    "CALosAngeles", "Los_angeles_avito", "Los_Angeles_Reklama", "la_chat_work", "LAchatik", "kvartira_new_york",
    "renthouselup", "NewYork_Go_Travel", "kvartirnii_vopros_NY", "new_york_citychat", "ads_new_york", "nyjobsusa",
    "ukrnewyorkgroup", "NYchatik", "newyorkfriend", "svoiny", "NewYork_info", "ChatNewYork1", "rentinNewYokkChat",
    "new_york_avito", "Ukraine_in_USA", "NYCmarket", "Gorodskoy_chat_NY", "JobsInNewYork", "NashNY", "Nyjobs_usa",
    "usaforuz", "NewYorkNash1", "sportmiami", "miami_livechat", "MiamiChatik", "MIAMI_HELP", "maiami_are",
    "Miami_Avito_Go", "gorodskoy_chat_miami", "Miami_GoTravel", "miamskiyydvizh", "ours_chat_miami2",
    "MiamiFloridainfo", "miami_helps", "miamired", "miami_services", "miamiarea", "miamifriends", "miami_chat_rus",
    "Miami_avito", "businessMiamii", "CA_Miami_Chat", "NashMiami", "gorodskoy_chat_miami", "Jobs1nChicago",
    "BazMeetChicago", "rentinChicagoChat", "Obshchaya_Sbor_Chikago", "ChicagoIL", "chired", "CHchatUA", "NashChicago",
    "chicago_avito", "chicagoass", "jobs1nSeattle", "Seattle_avito", "seattlered", "rentinSiettleChat",
    "businessSiettle", "sacramentocity", "SacramentoinChat", "businessSacrament0", "ctatinSacramento",
    "rentinSacramentoChat", "sacramentored", "adaptationinsacramento", "cNecRg9IeLlkNmUx", "Washington_life", "usa_360",
    "Obmenik_USA", "UsaExchangeChat", "exchange_chat_usa", "usb_mexico_usa", "dhdhdhfhfhfh", "VATANDOSHIM_USA_50_state",
    "uzbeksinusalup", "YagonadarchausaNY", "VatandoshimYGU", "chatamerika", "ours_app", "vatandoshimuzbus",
    "Vatandoshim_uz", "pets_delivery_usa_europe_canada", "chatamericaUA", "biznesdvigusa", "Poruchiteli", "Horizont24",
    "dogbanusa", "americaindetails", "poputchiki_usa", "adaptaciya_UA_USA", "mahallanewyorkjobs", "usa_benefit",
    "poruschitel", "USA_job_helper", "USA_job_help", "YagonadarchausaNY", "usamexico", "USACHATRU", "mexicoUSA21",
    "Works_usa", "UZimiznikilarCOM", "jobs_usa24", "nomadsfamilyusa", "chatinSF", "chat_rusrek_sanfrancisco",
    "san_francisco_avito", "jobsinSF", "rentinSanFranciscoChat", "SanFranciscoinChat", "businessSanFrancisco",
    "WorldCalifornia", "NashaPhiladelphia", "philadelphiafriends", "Chat_Philadelphia_RusRek",
    "philadelpia_pennsylvania", "rentinPhiladelphiaChat", "businessPhiladelphia", "Philadelphiachat", "phillychat",
    "chatinNJ", "BazMeetNewJersey", "businessNewJersey",
]
